title: Madhu Surisetti
author:
  name: Madhu Surisetti
  email: madhu at madhusurisetti.com
domain: madhusurisetti.com
google_analytics: G-659S208QCP
footer_home_msg: Made by Madhu Surisetti
footer_essay_msg: Thank you for reading




















# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - subscribe.md
  - whoami.md

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic
  social_links:
    - { platform: github,         user_url: "https://github.com/Write2Hack/blog" }
    - { platform: twitter,        user_url: "https://twitter.com/QuantumFlight" }
    - { platform: x,              user_url: "https://x.com/QuantumFlight" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
